import type {
  AdminUserProfile,
  Booking,
  Resource,
  UserProfile,
  Venue,
} from "../../../../../../Downloads/b_tS9Lg5ICdHP-1771876862951/lib/types";

// ── Admin user ──────────────────────────────────────────────────
export const adminUser: UserProfile = {
  id: "admin-1",
  email: "admin@sportshub.es",
  displayName: "Admin SportsHub",
  description: "Administrador de la plataforma",
  phoneNumber: "+34 600 000 001",
  preferredSport: null,
  skillLevel: null,
  city: "Madrid",
  countryCode: "ES",
  avatarUrl: null,
  role: "ADMIN",
  ownerRequestStatus: null,
  onboardingCompleted: true,
  lastLoginAt: "2026-02-23T08:00:00Z",
};

// ── Pending owner requests ──────────────────────────────────────
export const pendingOwners: AdminUserProfile[] = [
  {
    id: "user-10",
    email: "pedro.garcia@email.com",
    displayName: "Pedro Garcia",
    description: "Quiero registrar mi club de padel en Sevilla.",
    phoneNumber: "+34 611 222 333",
    preferredSport: "PADEL",
    skillLevel: "ADVANCED",
    city: "Sevilla",
    countryCode: "ES",
    avatarUrl: null,
    role: "PLAYER",
    ownerRequestStatus: "PENDING",
    onboardingCompleted: true,
    lastLoginAt: "2026-02-22T15:00:00Z",
    active: true,
    emailVerified: true,
    createdAt: "2026-01-10T10:00:00Z",
    updatedAt: "2026-02-22T15:00:00Z",
  },
  {
    id: "user-11",
    email: "maria.lopez@email.com",
    displayName: "Maria Lopez",
    description: "Gestiono 3 instalaciones deportivas en Barcelona.",
    phoneNumber: "+34 622 333 444",
    preferredSport: "TENNIS",
    skillLevel: "INTERMEDIATE",
    city: "Barcelona",
    countryCode: "ES",
    avatarUrl: null,
    role: "PLAYER",
    ownerRequestStatus: "PENDING",
    onboardingCompleted: true,
    lastLoginAt: "2026-02-21T11:00:00Z",
    active: true,
    emailVerified: true,
    createdAt: "2026-01-20T09:00:00Z",
    updatedAt: "2026-02-21T11:00:00Z",
  },
];

// ── Pending venues ──────────────────────────────────────────────
export const pendingVenues: Venue[] = [
  {
    id: "venue-7",
    ownerId: "owner-1",
    name: "Club Padel Retiro",
    description:
      "Nuevo club junto al Retiro con 6 pistas de padel cubiertas y 2 al aire libre. Vestuarios completos y parking.",
    street: "Calle Alcala 100",
    city: "Madrid",
    country: "ES",
    postalCode: "28009",
    latitude: 40.4168,
    longitude: -3.6836,
    status: "PENDING_REVIEW",
    rejectReason: null,
    images: [
      { id: "pv-1", url: "/images/venues/venue-2.jpg", displayOrder: 0 },
    ],
    resourceCount: 0,
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-02-01T10:00:00Z",
  },
  {
    id: "venue-20",
    ownerId: "user-10",
    name: "Padel Triana Sevilla",
    description:
      "Club de padel en el corazon de Triana con 4 pistas panoramicas y vistas al Guadalquivir.",
    street: "Calle Betis 40",
    city: "Sevilla",
    country: "ES",
    postalCode: "41010",
    latitude: 37.3826,
    longitude: -6.0035,
    status: "PENDING_REVIEW",
    rejectReason: null,
    images: [
      { id: "pv-2", url: "/images/venues/venue-4.jpg", displayOrder: 0 },
    ],
    resourceCount: 0,
    createdAt: "2026-02-18T14:00:00Z",
    updatedAt: "2026-02-18T14:00:00Z",
  },
  {
    id: "venue-21",
    ownerId: "user-11",
    name: "Barcelona Tennis Club",
    description: "Club de tenis con 3 pistas de tierra batida y 2 de padel.",
    street: "Avinguda Diagonal 500",
    city: "Barcelona",
    country: "ES",
    postalCode: "08006",
    latitude: 41.3954,
    longitude: 2.1532,
    status: "PENDING_REVIEW",
    rejectReason: null,
    images: [],
    resourceCount: 0,
    createdAt: "2026-02-20T09:00:00Z",
    updatedAt: "2026-02-20T09:00:00Z",
  },
];

// ── Pending resources ───────────────────────────────────────────
export const pendingResources: Resource[] = [
  {
    id: "res-20a",
    venueId: "venue-1",
    name: "Pista 3 - Premium",
    description: "Pista premium con iluminacion LED y cristal panoramico de ultima generacion.",
    type: "PADEL",
    slotDurationMinutes: 90,
    status: "PENDING_REVIEW",
    rejectReason: null,
    schedules: [],
    priceRules: [],
    images: [
      { id: "primg-1", url: "/images/venues/venue-1.jpg", displayOrder: 0 },
    ],
    createdAt: "2026-02-10T10:00:00Z",
    updatedAt: "2026-02-10T10:00:00Z",
  },
  {
    id: "res-20b",
    venueId: "venue-20",
    name: "Pista Guadalquivir",
    description: "Pista con vistas al rio, cesped artificial de primera calidad.",
    type: "PADEL",
    slotDurationMinutes: 60,
    status: "PENDING_REVIEW",
    rejectReason: null,
    schedules: [],
    priceRules: [],
    images: [],
    createdAt: "2026-02-19T10:00:00Z",
    updatedAt: "2026-02-19T10:00:00Z",
  },
];

// ── All users (for admin user list) ─────────────────────────────
export const allUsers: AdminUserProfile[] = [
  {
    id: "admin-1",
    email: "admin@sportshub.es",
    displayName: "Admin SportsHub",
    description: null,
    phoneNumber: "+34 600 000 001",
    preferredSport: null,
    skillLevel: null,
    city: "Madrid",
    countryCode: "ES",
    avatarUrl: null,
    role: "ADMIN",
    ownerRequestStatus: null,
    onboardingCompleted: true,
    lastLoginAt: "2026-02-23T08:00:00Z",
    active: true,
    emailVerified: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2026-02-23T08:00:00Z",
  },
  {
    id: "owner-1",
    email: "propietario@sportshub.es",
    displayName: "Laura Fernandez",
    description: "Propietaria de clubs de padel en Madrid.",
    phoneNumber: "+34 600 123 456",
    preferredSport: "PADEL",
    skillLevel: "ADVANCED",
    city: "Madrid",
    countryCode: "ES",
    avatarUrl: null,
    role: "OWNER",
    ownerRequestStatus: "APPROVED",
    onboardingCompleted: true,
    lastLoginAt: "2026-02-23T08:00:00Z",
    active: true,
    emailVerified: true,
    createdAt: "2025-06-01T10:00:00Z",
    updatedAt: "2026-02-23T08:00:00Z",
  },
  {
    id: "user-1",
    email: "carlos@email.com",
    displayName: "Carlos Martinez",
    description: "Jugador de padel apasionado.",
    phoneNumber: "+34 612 345 678",
    preferredSport: "PADEL",
    skillLevel: "INTERMEDIATE",
    city: "Madrid",
    countryCode: "ES",
    avatarUrl: null,
    role: "PLAYER",
    ownerRequestStatus: "NONE",
    onboardingCompleted: true,
    lastLoginAt: "2026-02-22T09:00:00Z",
    active: true,
    emailVerified: true,
    createdAt: "2025-08-15T10:00:00Z",
    updatedAt: "2026-02-22T09:00:00Z",
  },
  ...pendingOwners,
];

// ── Recent bookings (all platform) ──────────────────────────────
export const allBookings: Booking[] = [
  {
    id: "ab-1",
    resourceId: "res-1a",
    playerId: "user-1",
    bookingDate: "2026-02-23",
    startTime: "18:00:00",
    endTime: "19:30:00",
    pricePaid: 24,
    currency: "EUR",
    status: "CONFIRMED",
    paymentStatus: "PAID",
    expiresAt: null,
    cancelledAt: null,
    cancelReason: null,
    createdAt: "2026-02-20T10:00:00Z",
    resourceName: "Pista Central",
    venueName: "Padel Club Madrid Centro",
    venueCity: "Madrid",
  },
  {
    id: "ab-2",
    resourceId: "res-1b",
    playerId: "user-2",
    bookingDate: "2026-02-23",
    startTime: "10:00:00",
    endTime: "11:00:00",
    pricePaid: 22,
    currency: "EUR",
    status: "CONFIRMED",
    paymentStatus: "PAID",
    expiresAt: null,
    cancelledAt: null,
    cancelReason: null,
    createdAt: "2026-02-21T14:00:00Z",
    resourceName: "Pista 2",
    venueName: "Padel Club Madrid Centro",
    venueCity: "Madrid",
  },
  {
    id: "ab-3",
    resourceId: "res-1a",
    playerId: "user-3",
    bookingDate: "2026-02-24",
    startTime: "09:00:00",
    endTime: "10:30:00",
    pricePaid: 18,
    currency: "EUR",
    status: "PENDING_PAYMENT",
    paymentStatus: "PENDING",
    expiresAt: "2026-02-23T20:15:00Z",
    cancelledAt: null,
    cancelReason: null,
    createdAt: "2026-02-22T08:00:00Z",
    resourceName: "Pista Central",
    venueName: "Padel Club Madrid Centro",
    venueCity: "Madrid",
  },
];

// ── Stats for admin dashboard ───────────────────────────────────
export const adminStats = {
  totalUsers: 156,
  totalOwners: 12,
  totalPlayers: 142,
  totalAdmins: 2,
  totalVenues: 24,
  activeVenues: 18,
  pendingVenues: pendingVenues.length,
  totalResources: 67,
  activeResources: 58,
  pendingResources: pendingResources.length,
  totalBookings: 1243,
  revenueThisMonth: 18450,
  pendingOwnerRequests: pendingOwners.length,
};
