import type {Booking, UserProfile, Venue} from "@/types";

export const mockUser: UserProfile = {
    id: "user-1",
    email: "carlos@email.com",
    displayName: "Carlos Martinez",
    description: "Jugador de padel apasionado. Siempre buscando partidos!",
    phoneNumber: "+34 612 345 678",
    preferredSport: "PADEL",
    skillLevel: "INTERMEDIATE",
    city: "Madrid",
    countryCode: "ES",
    avatarUrl: null,
    role: "PLAYER",
    ownerRequestStatus: "NONE",
    onboardingCompleted: true,
    lastLoginAt: "2026-02-22T09:00:00Z",
};

export const mockVenues: Venue[] = [
    {
        id: "venue-1",
        ownerId: "owner-1",
        name: "Padel Club Madrid Centro",
        description:
            "Club premium en el corazon de Madrid con 8 pistas de padel de cristal, vestuarios completos y zona de descanso con cafeteria.",
        street: "Calle Gran Via 45",
        city: "Madrid",
        country: "ES",
        postalCode: "28013",
        latitude: 40.4200,
        longitude: -3.7025,
        status: "ACTIVE",
        rejectReason: null,
        images: [
            {
                id: "img-1a",
                url: "/images/venues/venue-1.jpg",
                displayOrder: 0,
                alt: "Padel Club Madrid Centro - Pistas exteriores",
            },
        ],
        resourceCount: 8,
        createdAt: "2025-06-01T10:00:00Z",
        updatedAt: "2025-06-15T14:30:00Z",
    },
    {
        id: "venue-2",
        ownerId: "owner-2",
        name: "Barcelona Indoor Padel",
        description:
            "Centro indoor con 12 pistas cubiertas, iluminacion LED profesional y suelo de ultima generacion. Abierto todo el ano.",
        street: "Avinguda Diagonal 320",
        city: "Barcelona",
        country: "ES",
        postalCode: "08013",
        latitude: 41.3925,
        longitude: 2.1541,
        status: "ACTIVE",
        rejectReason: null,
        images: [
            {
                id: "img-2a",
                url: "/images/venues/venue-2.jpg",
                displayOrder: 0,
                alt: "Barcelona Indoor Padel - Interior",
            },
        ],
        resourceCount: 12,
        createdAt: "2025-05-20T08:00:00Z",
        updatedAt: "2025-06-10T09:15:00Z",
    },
    {
        id: "venue-3",
        ownerId: "owner-3",
        name: "Padel Playa Valencia",
        description:
            "Pistas de padel junto al mar con vistas al Mediterraneo. Ambiente relajado, clases para todos los niveles y torneos semanales.",
        street: "Paseo Maritimo 12",
        city: "Valencia",
        country: "ES",
        postalCode: "46011",
        latitude: 39.4561,
        longitude: -0.3545,
        status: "ACTIVE",
        rejectReason: null,
        images: [
            {
                id: "img-3a",
                url: "/images/venues/venue-3.jpg",
                displayOrder: 0,
                alt: "Padel Playa Valencia - Vista exterior",
            },
        ],
        resourceCount: 6,
        createdAt: "2025-04-15T12:00:00Z",
        updatedAt: "2025-06-12T16:45:00Z",
    },
    {
        id: "venue-4",
        ownerId: "owner-4",
        name: "Padel Night Sevilla",
        description:
            "Experiencia nocturna unica. Pistas iluminadas con tecnologia LED, musica ambiente y bar deportivo. Abierto hasta las 2AM.",
        street: "Avenida de la Constitucion 28",
        city: "Sevilla",
        country: "ES",
        postalCode: "41004",
        latitude: 37.3826,
        longitude: -5.9965,
        status: "ACTIVE",
        rejectReason: null,
        images: [
            {
                id: "img-4a",
                url: "/images/venues/venue-4.jpg",
                displayOrder: 0,
                alt: "Padel Night Sevilla - Pistas nocturnas",
            },
        ],
        resourceCount: 5,
        createdAt: "2025-03-10T18:00:00Z",
        updatedAt: "2025-06-08T20:00:00Z",
    },
    {
        id: "venue-5",
        ownerId: "owner-5",
        name: "Sky Padel Bilbao",
        description:
            "Pistas en azotea con vistas panoramicas a la ciudad. Techo retractil, climatizacion y parking gratuito para socios.",
        street: "Plaza Moyua 5",
        city: "Bilbao",
        country: "ES",
        postalCode: "48009",
        latitude: 43.2630,
        longitude: -2.9350,
        status: "ACTIVE",
        rejectReason: null,
        images: [
            {
                id: "img-5a",
                url: "/images/venues/venue-5.jpg",
                displayOrder: 0,
                alt: "Sky Padel Bilbao - Azotea",
            },
        ],
        resourceCount: 4,
        createdAt: "2025-02-20T09:00:00Z",
        updatedAt: "2025-06-05T11:30:00Z",
    },
    {
        id: "venue-6",
        ownerId: "owner-6",
        name: "Padel Garden Malaga",
        description:
            "Complejo deportivo familiar rodeado de jardines. 10 pistas, zona infantil, escuela de padel y restaurante con terraza.",
        street: "Calle Larios 15",
        city: "Malaga",
        country: "ES",
        postalCode: "29015",
        latitude: 36.7213,
        longitude: -4.4214,
        status: "ACTIVE",
        rejectReason: null,
        images: [
            {
                id: "img-6a",
                url: "/images/venues/venue-6.jpg",
                displayOrder: 0,
                alt: "Padel Garden Malaga - Complejo exterior",
            },
        ],
        resourceCount: 10,
        createdAt: "2025-01-15T07:00:00Z",
        updatedAt: "2025-06-14T13:00:00Z",
    },
    {
        id: "venue-7",
        ownerId: "owner-1",
        name: "Club Padel Retiro",
        description: "En revision por el equipo de SportsHub.",
        street: "Calle Alcala 100",
        city: "Madrid",
        country: "ES",
        postalCode: "28009",
        latitude: 40.4168,
        longitude: -3.6836,
        status: "PENDING_REVIEW",
        rejectReason: null,
        images: [],
        resourceCount: 3,
        createdAt: "2026-02-01T10:00:00Z",
        updatedAt: "2026-02-01T10:00:00Z",
    },
    {
        id: "venue-8",
        ownerId: "owner-2",
        name: "Padel Zone Suspendido",
        description: "Venue temporalmente suspendido.",
        street: "Carrer de Balmes 50",
        city: "Barcelona",
        country: "ES",
        postalCode: "08007",
        latitude: 41.3920,
        longitude: 2.1580,
        status: "SUSPENDED",
        rejectReason: null,
        images: [],
        resourceCount: 7,
        createdAt: "2025-08-01T10:00:00Z",
        updatedAt: "2026-01-20T10:00:00Z",
    },
];

export const availableCities = [
    "Todas",
    "Madrid",
    "Barcelona",
    "Valencia",
    "Sevilla",
    "Bilbao",
    "Malaga",
];

export const mockBookings: Booking[] = [
    {
        id: "booking-1",
        resourceId: "res-1a",
        playerId: "user-1",
        bookingDate: "2026-02-23",
        startTime: "18:00:00",
        endTime: "19:00:00",
        pricePaid: 24,
        currency: "EUR",
        status: "CONFIRMED",
        paymentStatus: "PAID",
        expiresAt: null,
        cancelledAt: null,
        cancelReason: null,
        createdAt: "2026-02-20T10:00:00Z",
        resourceName: "Pista Central",
        venueName: "Padel Club Madrid Centro",
        venueCity: "Madrid",
    },
    {
        id: "booking-2",
        resourceId: "res-3a",
        playerId: "user-1",
        bookingDate: "2026-02-25",
        startTime: "10:00:00",
        endTime: "11:30:00",
        pricePaid: 30,
        currency: "EUR",
        status: "CONFIRMED",
        paymentStatus: "PAID",
        expiresAt: null,
        cancelledAt: null,
        cancelReason: null,
        createdAt: "2026-02-21T14:00:00Z",
        resourceName: "Pista Mar",
        venueName: "Padel Playa Valencia",
        venueCity: "Valencia",
    },
    {
        id: "booking-3",
        resourceId: "res-4a",
        playerId: "user-1",
        bookingDate: "2026-02-20",
        startTime: "21:00:00",
        endTime: "22:00:00",
        pricePaid: 28,
        currency: "EUR",
        status: "CONFIRMED",
        paymentStatus: "PAID",
        expiresAt: null,
        cancelledAt: null,
        cancelReason: null,
        createdAt: "2026-02-18T09:00:00Z",
        resourceName: "Pista Noche 1",
        venueName: "Padel Night Sevilla",
        venueCity: "Sevilla",
    },
    {
        id: "booking-4",
        resourceId: "res-1b",
        playerId: "user-1",
        bookingDate: "2026-02-15",
        startTime: "17:00:00",
        endTime: "18:00:00",
        pricePaid: 22,
        currency: "EUR",
        status: "CANCELLED",
        paymentStatus: "REFUNDED",
        expiresAt: null,
        cancelledAt: "2026-02-14T20:00:00Z",
        cancelReason: "No pude asistir",
        createdAt: "2026-02-12T11:00:00Z",
        resourceName: "Pista 2",
        venueName: "Padel Club Madrid Centro",
        venueCity: "Madrid",
    },
];
