import type {Booking, Resource, UserProfile, Venue} from "@/types";

export const ownerUser: UserProfile = {
  id: "owner-1",
  email: "propietario@sportshub.es",
  displayName: "Laura Fernandez",
  description: "Propietaria de clubs de padel en Madrid. Apasionada del deporte.",
  phoneNumber: "+34 600 123 456",
  preferredSport: "PADEL",
  skillLevel: "ADVANCED",
  city: "Madrid",
  countryCode: "ES",
  avatarUrl: null,
  role: "OWNER",
  ownerRequestStatus: "APPROVED",
  onboardingCompleted: true,
  lastLoginAt: "2026-02-23T08:00:00Z",
};

export const ownerVenues: Venue[] = [
  {
    id: "venue-1",
    ownerId: "owner-1",
    name: "Padel Club Madrid Centro",
    description: "Club premium en el corazon de Madrid con 8 pistas de padel de cristal, vestuarios completos y zona de descanso con cafeteria.",
    street: "Calle Gran Via 45",
    city: "Madrid",
    country: "ES",
    postalCode: "28013",
    latitude: 40.4200,
    longitude: -3.7025,
    status: "ACTIVE",
    rejectReason: null,
    images: [
      { id: "img-1a", url: "/images/venues/venue-1.jpg", displayOrder: 0, alt: "Pistas exteriores" },
    ],
    resourceCount: 3,
    createdAt: "2025-06-01T10:00:00Z",
    updatedAt: "2025-06-15T14:30:00Z",
  },
  {
    id: "venue-7",
    ownerId: "owner-1",
    name: "Club Padel Retiro",
    description: "Nuevo club junto al Retiro. Pendiente de aprobacion.",
    street: "Calle Alcala 100",
    city: "Madrid",
    country: "ES",
    postalCode: "28009",
    latitude: 40.4168,
    longitude: -3.6836,
    status: "PENDING_REVIEW",
    rejectReason: null,
    images: [],
    resourceCount: 0,
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-02-01T10:00:00Z",
  },
  {
    id: "venue-9",
    ownerId: "owner-1",
    name: "Padel Sur Madrid",
    description: "Rechazado: falta documentacion legal.",
    street: "Avenida de los Poblados 12",
    city: "Madrid",
    country: "ES",
    postalCode: "28033",
    latitude: 40.3800,
    longitude: -3.6600,
    status: "REJECTED",
    rejectReason: "Falta documentacion legal: licencia de actividad y seguro de responsabilidad civil.",
    images: [],
    resourceCount: 0,
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-01-20T10:00:00Z",
  },
];

export const ownerResources: Resource[] = [
  {
    id: "res-1a",
    venueId: "venue-1",
    name: "Pista Central",
    description: "Pista principal con cristal panoramico y grada para espectadores.",
    type: "PADEL",
    slotDurationMinutes: 90,
    status: "ACTIVE",
    rejectReason: null,
    schedules: [
      { dayOfWeek: "MON", openingTime: "07:00", closingTime: "22:00" },
      { dayOfWeek: "TUE", openingTime: "07:00", closingTime: "22:00" },
      { dayOfWeek: "WED", openingTime: "07:00", closingTime: "22:00" },
      { dayOfWeek: "THU", openingTime: "07:00", closingTime: "22:00" },
      { dayOfWeek: "FRI", openingTime: "07:00", closingTime: "23:00" },
      { dayOfWeek: "SAT", openingTime: "08:00", closingTime: "23:00" },
      { dayOfWeek: "SUN", openingTime: "08:00", closingTime: "21:00" },
    ],
    priceRules: [
      { id: "pr-1", dayType: "WEEKDAY", startTime: "07:00", endTime: "14:00", price: 18, currency: "EUR" },
      { id: "pr-2", dayType: "WEEKDAY", startTime: "14:00", endTime: "22:00", price: 24, currency: "EUR" },
      { id: "pr-3", dayType: "WEEKEND", startTime: "08:00", endTime: "23:00", price: 30, currency: "EUR" },
    ],
    images: [
      { id: "rimg-1a", url: "/images/venues/venue-1.jpg", displayOrder: 0 },
    ],
    createdAt: "2025-06-05T10:00:00Z",
    updatedAt: "2025-06-10T12:00:00Z",
  },
  {
    id: "res-1b",
    venueId: "venue-1",
    name: "Pista 2",
    description: "Pista cubierta con cesped artificial de ultima generacion.",
    type: "PADEL",
    slotDurationMinutes: 60,
    status: "ACTIVE",
    rejectReason: null,
    schedules: [
      { dayOfWeek: "MON", openingTime: "08:00", closingTime: "22:00" },
      { dayOfWeek: "TUE", openingTime: "08:00", closingTime: "22:00" },
      { dayOfWeek: "WED", openingTime: "08:00", closingTime: "22:00" },
      { dayOfWeek: "THU", openingTime: "08:00", closingTime: "22:00" },
      { dayOfWeek: "FRI", openingTime: "08:00", closingTime: "23:00" },
      { dayOfWeek: "SAT", openingTime: "09:00", closingTime: "23:00" },
      { dayOfWeek: "SUN", openingTime: "09:00", closingTime: "20:00" },
    ],
    priceRules: [
      { id: "pr-4", dayType: "WEEKDAY", startTime: "08:00", endTime: "14:00", price: 16, currency: "EUR" },
      { id: "pr-5", dayType: "WEEKDAY", startTime: "14:00", endTime: "22:00", price: 22, currency: "EUR" },
      { id: "pr-6", dayType: "WEEKEND", startTime: "09:00", endTime: "23:00", price: 28, currency: "EUR" },
    ],
    images: [],
    createdAt: "2025-06-05T11:00:00Z",
    updatedAt: "2025-06-10T12:00:00Z",
  },
  {
    id: "res-1c",
    venueId: "venue-1",
    name: "Pista 3 - Premium",
    description: "Pista premium pendiente de revision.",
    type: "PADEL",
    slotDurationMinutes: 90,
    status: "PENDING_REVIEW",
    rejectReason: null,
    schedules: [],
    priceRules: [],
    images: [],
    createdAt: "2026-02-10T10:00:00Z",
    updatedAt: "2026-02-10T10:00:00Z",
  },
];

export const ownerBookings: Booking[] = [
  {
    id: "ob-1",
    resourceId: "res-1a",
    playerId: "user-1",
    bookingDate: "2026-02-23",
    startTime: "18:00:00",
    endTime: "19:30:00",
    pricePaid: 24,
    currency: "EUR",
    status: "CONFIRMED",
    paymentStatus: "PAID",
    expiresAt: null,
    cancelledAt: null,
    cancelReason: null,
    createdAt: "2026-02-20T10:00:00Z",
    resourceName: "Pista Central",
    venueName: "Padel Club Madrid Centro",
    venueCity: "Madrid",
  },
  {
    id: "ob-2",
    resourceId: "res-1b",
    playerId: "user-2",
    bookingDate: "2026-02-23",
    startTime: "10:00:00",
    endTime: "11:00:00",
    pricePaid: 22,
    currency: "EUR",
    status: "CONFIRMED",
    paymentStatus: "PAID",
    expiresAt: null,
    cancelledAt: null,
    cancelReason: null,
    createdAt: "2026-02-21T14:00:00Z",
    resourceName: "Pista 2",
    venueName: "Padel Club Madrid Centro",
    venueCity: "Madrid",
  },
  {
    id: "ob-3",
    resourceId: "res-1a",
    playerId: "user-3",
    bookingDate: "2026-02-24",
    startTime: "09:00:00",
    endTime: "10:30:00",
    pricePaid: 18,
    currency: "EUR",
    status: "CONFIRMED",
    paymentStatus: "PAID",
    expiresAt: null,
    cancelledAt: null,
    cancelReason: null,
    createdAt: "2026-02-22T08:00:00Z",
    resourceName: "Pista Central",
    venueName: "Padel Club Madrid Centro",
    venueCity: "Madrid",
  },
  {
    id: "ob-4",
    resourceId: "res-1b",
    playerId: "user-4",
    bookingDate: "2026-02-22",
    startTime: "17:00:00",
    endTime: "18:00:00",
    pricePaid: 22,
    currency: "EUR",
    status: "CANCELLED",
    paymentStatus: "REFUNDED",
    expiresAt: null,
    cancelledAt: "2026-02-21T20:00:00Z",
    cancelReason: "Lesion",
    createdAt: "2026-02-19T11:00:00Z",
    resourceName: "Pista 2",
    venueName: "Padel Club Madrid Centro",
    venueCity: "Madrid",
  },
  {
    id: "ob-5",
    resourceId: "res-1a",
    playerId: "user-5",
    bookingDate: "2026-02-25",
    startTime: "20:00:00",
    endTime: "21:30:00",
    pricePaid: 24,
    currency: "EUR",
    status: "PENDING_PAYMENT",
    paymentStatus: "PENDING",
    expiresAt: "2026-02-23T20:15:00Z",
    cancelledAt: null,
    cancelReason: null,
    createdAt: "2026-02-23T19:50:00Z",
    resourceName: "Pista Central",
    venueName: "Padel Club Madrid Centro",
    venueCity: "Madrid",
  },
];
